version: '3.8'

services:
  jenkins:
    build: 
      context: ./jenkins-setup
    container_name: jenkins-blueocean
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      # Mount docker socker to allow Jenkins to run docker commands
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount casc.yaml to a stable location to avoid being masked by jenkins_home volume
      - ./jenkins-setup/casc.yaml:/var/jenkins_home/casc.yaml
    environment:
      # Pre-configure Java options if needed
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
    networks:
      - jenkins

networks:
  jenkins:
